"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { localizeApiError, sectorEnglish, ui } from "../../lib/i18n";
import BrandMark from "./BrandMark";
import { LanguageToggle, useLanguage } from "./LanguageProvider";
type ProfileJob={id:string;status:"queued"|"running"|"completed"|"failed";stage:"queued"|"annual_report"|"extract"|"compose"|"translate"|"validate"|"write"|"completed";progress:number;attempt:number;updatedAt:string;error:string|null};
type Entry={mappingId:number;code:string;name:string;nameEn?:string;profileJob?:ProfileJob;sectorId:number;sectorSlug:string;sectorName:string;role:"core"|"candidate";thesis:string;rationale:string;active:boolean};
type Form={mappingId?:number;code:string;name:string;sectorId:string;role:"core"|"candidate";thesis:string;rationale:string;active:boolean};
const empty:Form={code:"",name:"",sectorId:"",role:"core",thesis:"",rationale:"",active:true};
export default function AdminConsole(){const{locale}=useLanguage(),copy=adminCopy[locale],globalCopy=ui[locale],[ready,setReady]=useState(false),[configured,setConfigured]=useState(true),[authed,setAuthed]=useState(false),[password,setPassword]=useState(""),[error,setError]=useState(""),[entries,setEntries]=useState<Entry[]>([]),[form,setForm]=useState<Form>(empty),[saving,setSaving]=useState(false),[enrichingCode,setEnrichingCode]=useState(""),[filter,setFilter]=useState("");
 async function load(){const r=await fetch("/api/admin/companies",{cache:"no-store"});if(r.status===401){setAuthed(false);return}const j=await r.json();setEntries(j.entries??[])}
 useEffect(()=>{fetch("/api/admin/session",{cache:"no-store"}).then(r=>r.json()).then(s=>{setConfigured(s.configured);setAuthed(s.authenticated);setReady(true);if(s.authenticated)load()})},[]);
 const hasActiveProfileJobs=entries.some(entry=>entry.profileJob?.status==="queued"||entry.profileJob?.status==="running");
 useEffect(()=>{if(!authed||!hasActiveProfileJobs)return;const timer=window.setInterval(()=>{void load()},3000);return()=>window.clearInterval(timer)},[authed,hasActiveProfileJobs]);
 const sectors=useMemo(()=>[...new Map(entries.map(e=>[e.sectorId,{id:e.sectorId,slug:e.sectorSlug,name:e.sectorName}])).values()],[entries]); const visible=entries.filter(e=>!filter||`${e.name}${e.nameEn??""}${e.code}${e.sectorName}`.toLowerCase().includes(filter.toLowerCase())); const activeEntries=entries.filter(e=>e.active); const activeCompanyCount=new Set(activeEntries.map(e=>e.code)).size;
 async function login(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const j=await r.json();if(!r.ok){setError(j.error);return}setAuthed(true);setPassword("");await load()}
 async function enrich(code:string){setEnrichingCode(code);const r=await fetch("/api/admin/companies/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});const j=await r.json();setEnrichingCode("");await load();if(!r.ok){setError(`${copy.chineseSaved} ${localizeApiError(j.error,locale)}`);return false}setError("");return true}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");const method=form.mappingId?"PUT":"POST";const payload={...form,mappingId:form.mappingId,sectorId:Number(form.sectorId)};const r=await fetch("/api/admin/companies",{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){setSaving(false);setError(j.error);return}setForm(empty);await load();setSaving(false)}
 async function remove(mappingId:number,name:string){if(!window.confirm(copy.confirmDelete(name)))return;await fetch("/api/admin/companies",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({mappingId})});if(form.mappingId===mappingId)setForm(empty);await load()}
 function edit(e:Entry){setForm({mappingId:e.mappingId,code:e.code,name:e.name,sectorId:String(e.sectorId),role:e.role,thesis:e.thesis,rationale:e.rationale,active:e.active});window.scrollTo({top:0,behavior:"smooth"})}
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});setAuthed(false);setEntries([])}
 if(!ready)return <div className="admin-center">{copy.checking}</div>;
 if(!configured)return <div className="admin-center"><div className="login-card"><BrandMark/><LanguageToggle/><h1>{copy.notEnabled}</h1><p>{copy.notEnabledDetail}</p><a href="/">{copy.back}</a></div></div>;
 if(!authed)return <div className="admin-center"><form className="login-card" onSubmit={login}><BrandMark/><LanguageToggle/><p className="eyebrow"><span/>ADMIN ACCESS</p><h1>{copy.manage}</h1><p>{copy.loginDetail}</p><label>{copy.password}<input type="password" autoFocus autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••••••"/></label>{error&&<div className="form-error">{localizeApiError(error,locale)}</div>}<button className="primary-button" type="submit">{copy.signIn}</button><a href="/">{copy.back}</a></form></div>;
 return <main className="admin-shell"><header><a className="brand" href="/"><BrandMark/><span>{globalCopy.brand}</span><em>ADMIN</em></a><div><LanguageToggle/><span>{copy.signedIn}</span><button onClick={logout}>{copy.signOut}</button></div></header><section className="admin-heading"><div><p className="eyebrow"><span/>WATCHLIST CONTROL</p><h1>{copy.management}</h1><p>{copy.headingDetail}</p></div><div><strong>{activeCompanyCount}</strong><span>{copy.activeCompanies}<br/>{activeEntries.length} {copy.industryMappings}</span></div></section>
 <section className="admin-grid"><form className="editor-card" onSubmit={save}><header><h2>{form.mappingId?copy.editTarget:copy.addTarget}</h2>{form.mappingId&&<button type="button" onClick={()=>setForm(empty)}>{copy.cancelEdit}</button>}</header><div className="field-row"><label>{copy.stockCode}<input value={form.code} disabled={Boolean(form.mappingId)} maxLength={6} onChange={e=>setForm({...form,code:e.target.value.replace(/\D/g,"")})} placeholder={copy.codeExample}/></label><label>{copy.companyName}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={copy.nameExample}/></label></div><div className="field-row"><label>{copy.industrySegment}<select value={form.sectorId} onChange={e=>setForm({...form,sectorId:e.target.value})}><option value="">{copy.select}</option>{sectors.map(s=><option value={s.id} key={s.id}>{locale==="en"?sectorEnglish[s.slug]?.name??s.name:s.name}</option>)}</select></label><label>{copy.leaderType}<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Form["role"]})}><option value="core">{globalCopy.roleCore}</option><option value="candidate">{globalCopy.roleCandidate}</option></select></label></div><label>{copy.selectionLogic}<textarea value={form.thesis} onChange={e=>setForm({...form,thesis:e.target.value})} placeholder={copy.logicPlaceholder} rows={4}/></label><label>{copy.segmentNote}<textarea value={form.rationale} onChange={e=>setForm({...form,rationale:e.target.value})} placeholder={copy.notePlaceholder} rows={3}/></label><label className="switch"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span/>{copy.showPublicly}</label>{error&&<div className="form-error">{localizeApiError(error,locale)}</div>}<button className="save-button" disabled={saving}>{saving?copy.saving:form.mappingId?copy.saveChanges:copy.addToMap}</button></form>
 <div className="admin-list"><div className="admin-list-head"><div><h2>{copy.currentTargets}</h2><span>{visible.length} {copy.industryMappings}</span></div><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder={copy.search}/></div><div className="admin-rows">{visible.map(e=><article className={!e.active?"inactive":""} key={e.mappingId}><div><strong>{locale==="en"&&e.nameEn?e.nameEn:e.name}</strong><small>{e.code}</small>{e.profileJob&&<small className={`profile-job-status ${e.profileJob.status}`} title={e.profileJob.error??undefined}>{profileJobLabel(e.profileJob,copy)}</small>}</div><span>{locale==="en"?sectorEnglish[e.sectorSlug]?.name??e.sectorName:e.sectorName}</span><em className={e.role}>{e.role==="core"?globalCopy.roleCore:globalCopy.roleCandidate}</em><div className="row-actions"><button disabled={Boolean(enrichingCode)||e.profileJob?.status==="queued"||e.profileJob?.status==="running"} onClick={()=>enrich(e.code)}>{enrichingCode===e.code?copy.enriching:e.profileJob?.status==="failed"?copy.retryProfile:copy.refreshProfile}</button><button onClick={()=>edit(e)}>{copy.edit}</button><button className="danger" onClick={()=>remove(e.mappingId,e.name)}>{copy.delete}</button></div></article>)}</div></div></section></main>}

function profileJobLabel(job:ProfileJob,copy:typeof adminCopy.zh|typeof adminCopy.en){
 if(job.status==="completed")return copy.profileCompleted;
 if(job.status==="failed")return `${copy.profileFailed}${job.error?` · ${job.error}`:""}`;
 return `${copy.profileStages[job.stage]} · ${job.progress}%`;
}

const adminCopy={
 zh:{checking:"正在检查管理权限…",notEnabled:"管理后台尚未启用",notEnabledDetail:"发布时需要先设置管理员密码。网站前台不受影响。",back:"返回公开网站",manage:"管理算力标的",loginDetail:"请输入管理员密码。连续会话将在 7 天后自动失效。",password:"管理密码",signIn:"安全登录",signedIn:"管理员已登录",signOut:"退出",management:"标的管理",headingDetail:"填写中文资料后，系统将在后台检索年报、整理主营业务和产业业务、生成英文翻译，并在校验通过后写入数据库。",activeCompanies:"家有效公司",industryMappings:"条产业映射",editTarget:"编辑标的",addTarget:"添加新标的",cancelEdit:"取消编辑",stockCode:"股票代码",codeExample:"例如 688256",companyName:"公司简称",nameExample:"例如 寒武纪-U",industrySegment:"产业方向",select:"请选择",leaderType:"龙头类型",selectionLogic:"入选逻辑",logicPlaceholder:"说明公司的产业地位与核心能力",segmentNote:"本方向备注",notePlaceholder:"说明该公司与本产业环节的具体业务关系",showPublicly:"在公开网站展示",saving:"正在保存并启动资料处理…",saveChanges:"保存修改",addToMap:"添加到图谱",currentTargets:"当前标的",search:"搜索公司或产业方向",edit:"编辑",delete:"删除",enriching:"启动中…",retryProfile:"重试资料",refreshProfile:"更新资料",profileCompleted:"主营业务资料已完成",profileFailed:"资料处理失败",profileStages:{queued:"等待处理",annual_report:"检索年报",extract:"提取正文",compose:"整理主营业务",translate:"翻译英文",validate:"校验数据",write:"写入数据库",completed:"处理完成"},chineseSaved:"中文资料已保存。",confirmDelete:(name:string)=>`确认从该产业方向删除「${name}」？`},
 en:{checking:"Checking administrator access…",notEnabled:"Admin Console Not Enabled",notEnabledDetail:"Set an administrator password before publishing. The public site is unaffected.",back:"Back to Public Site",manage:"Manage Compute-Chain Companies",loginDetail:"Enter the administrator password. A continuous session expires after seven days.",password:"Administrator Password",signIn:"Secure Sign In",signedIn:"Administrator signed in",signOut:"Sign Out",management:"Company Management",headingDetail:"After the Chinese fields are saved, a background workflow retrieves the annual report, prepares the business profile and segment details, translates them, validates the result and writes it to the database.",activeCompanies:"active companies",industryMappings:"industry mappings",editTarget:"Edit Company",addTarget:"Add Company",cancelEdit:"Cancel",stockCode:"Stock Ticker",codeExample:"e.g. 688256",companyName:"Chinese Company Name",nameExample:"e.g. 寒武纪-U",industrySegment:"Industry Segment",select:"Select",leaderType:"Tracking Role",selectionLogic:"Chinese Selection Rationale",logicPlaceholder:"Describe the company’s industry position and core capabilities in Chinese",segmentNote:"Segment Note",notePlaceholder:"Describe the company’s specific business relationship to this segment",showPublicly:"Show on the public site",saving:"Saving and starting profile processing…",saveChanges:"Save Changes",addToMap:"Add to Map",currentTargets:"Current Companies",search:"Search company or industry segment",edit:"Edit",delete:"Delete",enriching:"Starting…",retryProfile:"Retry Profile",refreshProfile:"Refresh Profile",profileCompleted:"Business profile completed",profileFailed:"Profile processing failed",profileStages:{queued:"Queued",annual_report:"Retrieving annual report",extract:"Extracting business section",compose:"Preparing business profile",translate:"Translating into English",validate:"Validating data",write:"Writing to database",completed:"Completed"},chineseSaved:"Chinese profile saved.",confirmDelete:(name:string)=>`Remove “${name}” from this industry segment?`},
} as const;
