"use client";
import { useEffect, useMemo, useState } from "react";
type Company={code:string;name:string;thesis:string;exchange:string;role:"core"|"candidate";sectors:{sectorName:string;sectorShortName:string;role:string;rationale:string}[]};
type Detail={company:Company;quote:{price:number|null;changePct:number|null;change:number|null;high:number|null;low:number|null;open:number|null;prevClose:number|null;turnover:number|null;volumeRatio:number|null;amount:number|null}|null;history:{date:string;open:number;close:number;high:number;low:number;changePct:number}[];news:Item[];announcements:Item[];interpretation:{facts:string;evidence:string;verified:boolean}|null};
type Item={id:string;title:string;summary:string;time:string;source:string;url:string};
export default function CompanyDetail({initialCompany}:{initialCompany:Company}){const[data,setData]=useState<Detail|null>(null),[error,setError]=useState("");useEffect(()=>{fetch(`/api/company/${initialCompany.code}`).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.json()}).then(setData).catch(e=>setError(e.message))},[initialCompany.code]);const company=data?.company??initialCompany,q=data?.quote,h=useMemo(()=>data?.history??[],[data?.history]);const bounds=useMemo(()=>({min:h.length?Math.min(...h.map(p=>p.low)):0,max:h.length?Math.max(...h.map(p=>p.high)):1}),[h]);const five=periodChange(h,5),twenty=periodChange(h,20);
 return <main className="company-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">算</span><span>算力图谱</span><em>COMPANY BRIEF</em></a><nav><a href="/">← 返回产业全景</a><a className="admin-link" href="/admin">管理标的</a></nav></header><section className="company-hero"><div><p className="eyebrow"><span/>{company.exchange} · {company.code}</p><h1>{company.name}</h1><div className="company-tags">{company.sectors.map(s=><span key={s.sectorName}>{s.sectorShortName} · {s.role==="core"?"产业核心":"活跃候选"}</span>)}</div><p className="company-thesis">{company.thesis}</p></div><div className="quote-block"><span>最新价</span><strong>{q?.price==null?"—":`¥ ${format(q.price)}`}</strong><b className={(q?.changePct??0)>=0?"up":"down"}>{q?.changePct==null?"行情连接中":`${signed(q.changePct)}%  ${q.change==null?"":signed(q.change)}`}</b><small>免费公开行情源 · 可能存在延迟</small></div></section>
 <section className="quote-metrics"><div><span>今开</span><b>{num(q?.open)}</b></div><div><span>最高</span><b>{num(q?.high)}</b></div><div><span>最低</span><b>{num(q?.low)}</b></div><div><span>换手率</span><b>{pct(q?.turnover)}</b></div><div><span>量比</span><b>{num(q?.volumeRatio)}</b></div><div><span>近 5 日</span><b className={(five??0)>=0?"up":"down"}>{five==null?"—":`${signed(five)}%`}</b></div><div><span>近 20 日</span><b className={(twenty??0)>=0?"up":"down"}>{twenty==null?"—":`${signed(twenty)}%`}</b></div></section>
 <section className="company-content"><div className="main-column"><div className="detail-card price-card"><header><div><p className="eyebrow"><span/>RECENT MOVEMENT</p><h2>近期走势</h2></div><span>近 {h.length} 个交易日 · 前复权</span></header>{h.length?<div className="bar-chart">{h.map((p,i)=>{const range=bounds.max-bounds.min||1;const top=(bounds.max-p.high)/range*100;const height=Math.max((p.high-p.low)/range*100,2);const body=Math.max(Math.abs(p.close-p.open)/range*100,1.5);return <div className="price-bar" key={p.date} title={`${p.date} 收盘 ${p.close}`}><i style={{top:`${top}%`,height:`${height}%`}}/><b className={p.close>=p.open?"rise":"fall"} style={{top:`${(bounds.max-Math.max(p.open,p.close))/range*100}%`,height:`${body}%`}}/><span>{i%7===0?p.date.slice(5):""}</span></div>})}</div>:<div className="chart-empty">历史行情正在连接</div>}</div>
 <div className="detail-card"><header><div><p className="eyebrow"><span/>LEADER LOGIC</p><h2>龙头逻辑</h2></div></header><div className="thesis-box"><strong>核心判断</strong><p>{company.thesis}</p></div>{company.sectors.map(s=><div className="sector-rationale" key={s.sectorName}><span>{s.sectorName}</span><p>{s.rationale||company.thesis}</p></div>)}</div></div>
 <aside><div className="evidence-card"><p className="eyebrow"><span/>ANOMALY REVIEW</p><h2>异动解读</h2>{data?.interpretation?<><div className="evidence-fact"><span>盘面事实</span><p>{data.interpretation.facts}</p></div><div className={data.interpretation.verified?"evidence-source verified-source":"evidence-source"}><span>{data.interpretation.verified?"已匹配信息":"证据状态"}</span><p>{data.interpretation.evidence}</p></div></>:<p className="muted">当前未触发异动阈值，或行情数据正在连接。</p>}<small>系统只匹配事实，不对股价走势作预测。</small></div>{error&&<div className="data-notice">{error}</div>}<div className="disclaimer-card"><strong>研究提示</strong><p>核心标的表示产业跟踪价值，不代表估值合理或建议买入。请结合公告、财务数据和风险承受能力独立判断。</p></div></aside></section>
 <section className="company-news"><div className="section-heading"><div><p className="eyebrow"><span/>NEWS & FILINGS</p><h2>公司资讯与公告</h2></div></div><div className="news-columns"><div><h3>近期新闻</h3>{(data?.news??[]).map(n=><NewsRow item={n} key={n.id}/>)}{!data?.news.length&&<p className="muted">暂未获取到相关新闻。</p>}</div><div><h3>公司公告</h3>{(data?.announcements??[]).map(n=><NewsRow item={n} key={n.id}/>)}{!data?.announcements.length&&<p className="muted">暂未获取到最新公告。</p>}</div></div></section><footer className="site-footer"><a className="brand" href="/"><span className="brand-mark">算</span><span>算力图谱</span></a><p>数据仅供产业研究与信息参考，不构成任何投资建议。</p><span>© 2026 COMPUTE CHAIN</span></footer></main>}
function NewsRow({item}:{item:Item}){return <a className="detail-news-row" href={item.url} target="_blank" rel="noreferrer"><time>{item.time?item.time.slice(5,16):"最新"}</time><div><strong>{item.title}</strong><small>{item.source}</small></div><span>↗</span></a>}function periodChange(h:Detail["history"],days:number){if(h.length<2)return null;const end=h[h.length-1].close,start=h[Math.max(0,h.length-1-days)].close;return start?(end/start-1)*100:null}function format(v:number){return v.toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}function signed(v:number){return`${v>=0?"+":""}${v.toFixed(2)}`}function num(v:number|null|undefined){return v==null?"—":format(v)}function pct(v:number|null|undefined){return v==null?"—":`${v.toFixed(2)}%`}
