"use client";
import { useEffect, useMemo, useState } from "react";
import { hasEnglishCompany, isChineseContent, localizeApiError, localizeChineseFact, localizeCompany, localizeSource, matchesContentLanguage, sectorEnglish, ui } from "../../lib/i18n";
import { periodChange } from "../../lib/market-history";
import type { HistoryResult } from "../../lib/company-history";
import BrandMark from "./BrandMark";
import CompanyFinancials from "./CompanyFinancials";
import { LanguageToggle, useLanguage, type Locale } from "./LanguageProvider";
type Company={code:string;name:string;thesis:string;nameEn?:string;thesisEn?:string;enStatus?:string;exchange:string;role:"core"|"candidate";sectors:{sectorSlug:string;sectorName:string;sectorShortName:string;role:string;rationale:string}[]};
type HistoryPoint={date:string;open:number;close:number;high:number;low:number;changePct:number};
type Detail=HistoryResult & {company:Company;quote:{price:number|null;changePct:number|null;change:number|null;high:number|null;low:number|null;open:number|null;prevClose:number|null;turnover:number|null;volumeRatio:number|null;amount:number|null;marketCap:number|null}|null;history:HistoryPoint[];news:Item[];announcements:Item[];interpretation:{facts:string;evidence:string;verified:boolean}|null;relatedNews:Item|null};
type Item={id:string;title:string;summary:string;time:string;source:string;url:string};

export default function CompanyDetail({initialCompany}:{initialCompany:Company}) {
 const {locale}=useLanguage(),copy=detailCopy[locale],globalCopy=ui[locale];
 const [result,setResult]=useState<{code:string;locale:Locale;data:Detail}|null>(null);
 const [error,setError]=useState(""),[attempt,setAttempt]=useState(0),[historyBusy,setHistoryBusy]=useState(true);
 const data=result?.code===initialCompany.code&&result.locale===locale?result.data:null;
 useEffect(()=>{
  const controller=new AbortController();let active=true;let retryTimer:ReturnType<typeof setTimeout>|undefined;
  async function load(){
   try {
    const response=await fetch(`/api/company/${initialCompany.code}?lang=${locale}`,{signal:controller.signal,cache:"no-store"});
    if(!response.ok)throw new Error((await response.json()).error);
    const detail=await response.json() as Detail;
    if(!active)return;
    setError("");setResult({code:initialCompany.code,locale,data:detail});
    if(detail.history.length>=2&&detail.historyStatus!=="stale")return;
    // Retry only history; a temporary failure should not refetch news and all quotes.
    for(let retry=0;retry<2&&active;retry++){
     await new Promise<void>(resolve=>{retryTimer=setTimeout(resolve,(retry+1)*2000)});
     if(!active)return;
     try {
      const historyResponse=await fetch(`/api/company/${initialCompany.code}/history`,{signal:controller.signal,cache:"no-store"});
      if(!historyResponse.ok)continue;
      const next=await historyResponse.json() as HistoryResult;
      if(!active)return;
      if(next.history.length>=2)setResult(current=>current?.code===initialCompany.code&&current.locale===locale?{...current,data:{...current.data,...next}}:current);
      if(next.history.length>=2&&next.historyStatus==="current")return;
     }catch{if(!active)return;}
    }
   }catch(e){if(active)setError(e instanceof Error?e.message:"Request failed");}
   finally{if(active)setHistoryBusy(false);}
  }
  void load();
  return()=>{active=false;controller.abort();clearTimeout(retryTimer);};
 },[initialCompany.code,locale,attempt]);
 const retryHistory=()=>{setHistoryBusy(true);setAttempt(value=>value+1);};
 const rawCompany=data?.company??initialCompany,company=useMemo(()=>{const source=locale==="en"&&!hasEnglishCompany(rawCompany)?{...rawCompany,name:"English profile pending",thesis:"This company will appear on the English site after its verified English profile is complete."}:rawCompany;const translated=localizeCompany(source,locale);return{...translated,sectors:translated.sectors.map(s=>{const sector=locale==="en"?sectorEnglish[s.sectorSlug]:null;return sector?{...s,sectorName:sector.name,sectorShortName:sector.shortName,rationale:sector.description}:s})}},[rawCompany,locale]),q=data?.quote,h=useMemo(()=>data?.history??[],[data?.history]),news=(data?.news??[]).filter(item=>matchesContentLanguage(item.title,locale)),relatedNews=data?.relatedNews&&matchesContentLanguage(data.relatedNews.title,locale)?data.relatedNews:null;const five=periodChange(h,5),twenty=periodChange(h,20);
 return <main className="company-page"><header className="site-header"><a className="brand" href="/"><BrandMark/><span>{globalCopy.brand}</span><em>COMPANY BRIEF</em></a><nav aria-label={locale==="en"?"Main navigation":"主导航"}><a href="/">{globalCopy.navOverview}</a><a href="/signals">{globalCopy.navSignals}</a><a href="/news">{globalCopy.navNews}</a><a className="admin-link" href="/admin">{globalCopy.navAdmin}</a><LanguageToggle/></nav></header><section className="company-hero"><div><p className="eyebrow"><span/>{company.exchange} · {company.code}</p><h1>{company.name}</h1><div className="company-tags">{company.sectors.map(s=><span key={s.sectorName}>{s.sectorShortName} · {s.role==="core"?globalCopy.roleCore:globalCopy.roleCandidate}</span>)}</div><p className="company-thesis">{company.thesis}</p></div><div className="quote-block"><span>{copy.latestPrice}</span><strong>{q?.price==null?"—":`¥ ${format(q.price,locale)}`}</strong><b className={(q?.changePct??0)>=0?"up":"down"}>{q?.changePct==null?copy.connecting:`${signed(q.changePct)}%  ${q.change==null?"":signed(q.change)}`}</b><small>{copy.publicFeed}</small></div></section>
 <section className="quote-metrics" id="quote-metrics"><div><span>{globalCopy.latestPrice}</span><b>{q?.price==null?"—":`¥ ${format(q.price,locale)}`}</b></div><div><span>{globalCopy.todayChange}</span><b className={q?.changePct==null?undefined:q.changePct>=0?"up":"down"}>{q?.changePct==null?"—":`${signed(q.changePct)}%`}</b></div><div><span>{copy.open}</span><b>{num(q?.open,locale)}</b></div><div><span>{copy.high}</span><b>{num(q?.high,locale)}</b></div><div><span>{copy.low}</span><b>{num(q?.low,locale)}</b></div><div><span>{globalCopy.turnoverAmount}</span><b>{formatAmount(q?.amount,locale)}</b></div><div><span>{globalCopy.marketCap}</span><b>{formatMarketCap(q?.marketCap,locale)}</b></div><div><span>{copy.turnover}</span><b>{pct(q?.turnover)}</b></div><div><span>{copy.volumeRatio}</span><b>{num(q?.volumeRatio,locale)}</b></div><div><span>{copy.fiveDays}</span><b className={five==null?undefined:five>=0?"up":"down"}>{five==null?"—":`${signed(five)}%`}</b></div><div><span>{copy.twentyDays}</span><b className={twenty==null?undefined:twenty>=0?"up":"down"}>{twenty==null?"—":`${signed(twenty)}%`}</b></div></section>
 <section className="company-content"><div className="main-column"><div className="detail-card price-card"><header><div><p className="eyebrow"><span/>RECENT MOVEMENT</p><h2>{copy.recentMovement}</h2></div><span>{h.length?copy.lastDays(h.length):copy.forwardAdjusted}</span></header>{h.length>=2?<><PriceChart history={h} locale={locale}/>{data?.historyStatus==="stale"&&<p className="history-notice" role="status">{copy.historyStale(data.historyAsOf??h[h.length-1].date)} <button disabled={historyBusy} onClick={retryHistory}>{historyBusy?copy.retrying:copy.retry}</button></p>}</>:<div className="chart-empty" role="status">{h.length===1?<div><p>{copy.historyInsufficient(h.length)}</p><button disabled={historyBusy} onClick={retryHistory}>{historyBusy?copy.retrying:copy.retry}</button></div>:historyBusy?copy.historyLoading:<div><p>{copy.historyUnavailable}</p><button onClick={retryHistory}>{copy.retry}</button></div>}</div>}</div>
 </div>
 <aside><div className="evidence-card"><p className="eyebrow"><span/>ANOMALY REVIEW</p><h2>{copy.moveReview}</h2>{data?.interpretation?<><div className="evidence-fact"><span>{copy.marketFacts}</span><p>{localizeChineseFact(data.interpretation.facts,locale)}</p></div>{data.interpretation.verified&&relatedNews&&<div className="evidence-source verified-source"><span>{copy.matchedSource}</span><a className="evidence-article-link" href={relatedNews.url} target="_blank" rel="noreferrer">{locale==="en"?`Related event · ${relatedNews.title}`:data.interpretation.evidence}{locale==="en"&&isChineseContent(relatedNews.title)&&<small className="source-language-badge">{globalCopy.originalCn}</small>}</a></div>}</>:<p className="muted">{copy.noThreshold}</p>}<small>{copy.noPrediction}</small></div>{error&&<div className="data-notice">{localizeApiError(error,locale)}</div>}<div className="disclaimer-card"><strong>{copy.researchNote}</strong><p>{copy.disclaimer}</p></div></aside></section>
 <CompanyFinancials key={initialCompany.code} code={initialCompany.code}/>
 <section className="company-news"><div className="section-heading"><div><p className="eyebrow"><span/>NEWS & FILINGS</p><h2>{copy.newsAndFilings}</h2></div></div><div className="news-columns"><div><h3>{copy.recentNews}</h3>{news.map(n=><NewsRow item={n} locale={locale} key={n.id}/>)}{!news.length&&<p className="muted">{copy.noRelatedNews}</p>}</div><div><h3>{copy.companyFilings}</h3>{(data?.announcements??[]).map(n=><NewsRow item={n} locale={locale} key={n.id}/>)}{!data?.announcements.length&&<p className="muted">{copy.noFilings}</p>}</div></div></section><footer className="site-footer"><a className="brand" href="/"><BrandMark/><span>{globalCopy.brand}</span></a><p>{globalCopy.footer}</p><span>© 2026 COMPUTE CHAIN</span></footer></main>}

function PriceChart({history,locale}:{history:HistoryPoint[];locale:Locale}){
 const copy=detailCopy[locale];
 const[hovered,setHovered]=useState<number|null>(null);const width=820,height=330,left=58,right=18,top=18,bottom=44,plotWidth=width-left-right,plotHeight=height-top-bottom;
 const rawMin=Math.min(...history.map(p=>p.low)),rawMax=Math.max(...history.map(p=>p.high)),padding=Math.max((rawMax-rawMin)*.08,rawMax*.005),min=rawMin-padding,max=rawMax+padding,range=max-min||1;
 const x=(i:number)=>left+(i/Math.max(history.length-1,1))*plotWidth,y=(value:number)=>top+(max-value)/range*plotHeight;
 const line=history.map((p,i)=>`${i?"L":"M"}${x(i).toFixed(2)},${y(p.close).toFixed(2)}`).join(" "),area=`${line} L${x(history.length-1)},${top+plotHeight} L${left},${top+plotHeight} Z`;
 const yTicks=Array.from({length:5},(_,i)=>max-(range*i)/4),xIndexes=[0,Math.floor((history.length-1)/3),Math.floor((history.length-1)*2/3),history.length-1].filter((v,i,a)=>a.indexOf(v)===i),activeIndex=hovered??history.length-1,active=history[activeIndex],activeX=x(activeIndex),activeY=y(active.close),tooltipX=activeX>width-205?activeX-178:activeX+12,tooltipY=Math.max(12,Math.min(activeY-48,height-112));
 const locate=(clientX:number,rect:DOMRect)=>Math.max(0,Math.min(history.length-1,Math.round((((clientX-rect.left)/rect.width)*width-left)/plotWidth*(history.length-1))));
 return <div className="price-chart-shell"><svg className="price-chart-svg" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={copy.chartAria} tabIndex={0} onPointerMove={e=>setHovered(locate(e.clientX,e.currentTarget.getBoundingClientRect()))} onPointerLeave={()=>setHovered(null)} onPointerDown={e=>setHovered(locate(e.clientX,e.currentTarget.getBoundingClientRect()))} onFocus={()=>setHovered(history.length-1)} onKeyDown={e=>{if(e.key==="ArrowLeft")setHovered(Math.max(0,(hovered??history.length-1)-1));if(e.key==="ArrowRight")setHovered(Math.min(history.length-1,(hovered??history.length-1)+1))}}>
  <defs><linearGradient id="priceArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5f9a7d" stopOpacity=".28"/><stop offset="100%" stopColor="#5f9a7d" stopOpacity=".02"/></linearGradient></defs>
  {yTicks.map((tick,i)=><g key={tick}><line className="chart-grid-line" x1={left} y1={y(tick)} x2={width-right} y2={y(tick)}/><text className="chart-axis-label" x={left-10} y={y(tick)+3} textAnchor="end">{tick.toFixed(2)}</text>{i===4&&<text className="chart-axis-unit" x={8} y={top-18} textAnchor="start">{copy.priceUnit}</text>}</g>)}
  {xIndexes.map(i=><g key={i}><line className="chart-x-tick" x1={x(i)} y1={top+plotHeight} x2={x(i)} y2={top+plotHeight+5}/><text className="chart-axis-label" x={x(i)} y={height-15} textAnchor={i===0?"start":i===history.length-1?"end":"middle"}>{history[i].date.slice(5)}</text></g>)}
  <path className="chart-area" d={area}/><path className="chart-close-line" d={line}/>
  <line className="chart-hover-line" x1={activeX} y1={top} x2={activeX} y2={top+plotHeight}/><circle className="chart-hover-point" cx={activeX} cy={activeY} r="4"/>
  <g className="chart-tooltip" transform={`translate(${tooltipX},${tooltipY})`}><rect width="166" height="96" rx="3"/><text x="12" y="18" className="chart-tooltip-date">{active.date}</text><text x="12" y="40">{copy.openShort} {active.open.toFixed(2)} · {copy.closeShort} {active.close.toFixed(2)}</text><text x="12" y="60">{copy.highShort} {active.high.toFixed(2)} · {copy.lowShort} {active.low.toFixed(2)}</text><text x="12" y="80" className={active.changePct>=0?"tooltip-up":"tooltip-down"}>{copy.changeShort} {signed(active.changePct)}%</text></g>
 </svg><div className="chart-active-readout"><span>{active.date}</span><b>{copy.openShort} {active.open.toFixed(2)}</b><b>{copy.highShort} {active.high.toFixed(2)}</b><b>{copy.lowShort} {active.low.toFixed(2)}</b><b>{copy.closeShort} {active.close.toFixed(2)}</b><em className={active.changePct>=0?"up":"down"}>{signed(active.changePct)}%</em></div></div>
}

function NewsRow({item,locale}:{item:Item;locale:Locale}){return <a className="detail-news-row" href={item.url} target="_blank" rel="noreferrer"><time>{item.time?item.time.slice(5,16):ui[locale].latestNews}</time><div><strong>{item.title}</strong><small>{localizeSource(item.source,locale)}{locale==="en"&&isChineseContent(`${item.title}${item.summary}`)&&<span className="source-language-badge">{ui.en.originalCn}</span>}</small></div></a>}function format(v:number,locale:Locale){return v.toLocaleString(locale==="en"?"en-US":"zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}function signed(v:number){return`${v>=0?"+":""}${v.toFixed(2)}`}function num(v:number|null|undefined,locale:Locale){return v==null?"—":format(v,locale)}function pct(v:number|null|undefined){return v==null?"—":`${v.toFixed(2)}%`}

function formatAmount(value:number|null|undefined,locale:Locale){if(value==null)return"—";if(locale==="en")return value>=1e9?`¥${(value/1e9).toFixed(1)}bn`:`¥${(value/1e6).toFixed(0)}mn`;return value>=1e8?`${(value/1e8).toFixed(1)}亿`:`${(value/1e4).toFixed(0)}万`}
function formatMarketCap(value:number|null|undefined,locale:Locale){if(value==null)return"—";if(locale==="en")return value>=1e12?`¥${(value/1e12).toFixed(2)}tn`:`¥${(value/1e9).toFixed(value>=1e11?0:1)}bn`;return value>=1e12?`${(value/1e12).toFixed(2)}万亿`:`${(value/1e8).toFixed(value>=1e11?0:1)}亿`}

const detailCopy={
 zh:{latestPrice:"最新价",connecting:"行情连接中",publicFeed:"免费公开行情源 · 可能存在延迟",open:"今开",high:"最高",low:"最低",turnover:"换手率",volumeRatio:"量比",fiveDays:"近 5 日",twentyDays:"近 20 日",recentMovement:"近期走势",lastDays:(count:number)=>`近 ${count} 个交易日 · 前复权`,historyLoading:"历史行情加载中，连接失败时会自动重试…",historyUnavailable:"暂未获取到历史行情，请稍后重试。",historyInsufficient:(count:number)=>`仅获取到 ${count} 个交易日，暂不足以绘制走势。正在尝试备用行情源。`,historyStale:(date:string)=>`历史行情更新暂缓，显示截至 ${date} 的已保存数据。`,forwardAdjusted:"前复权",retry:"重新连接",retrying:"重试中…",leaderLogic:"龙头逻辑",coreView:"核心判断",moveReview:"异动解读",marketFacts:"盘面事实",matchedSource:"已匹配信息",noThreshold:"当前未触发异动阈值，或行情数据正在连接。",noPrediction:"系统只匹配事实，不对股价走势作预测。",researchNote:"研究提示",disclaimer:"核心标的表示产业跟踪价值，不代表估值合理或建议买入。请结合公告、财务数据和风险承受能力独立判断。",newsAndFilings:"公司资讯与公告",recentNews:"近期新闻",companyFilings:"公司公告",noRelatedNews:"暂未获取到相关新闻。",noFilings:"暂未获取到最新公告。",chartAria:"近期收盘价走势图，可用鼠标、触摸或键盘左右方向键查看每日开盘、收盘、最高和最低价",priceUnit:"价格（元）",openShort:"开",closeShort:"收",highShort:"高",lowShort:"低",changeShort:"涨跌"},
 en:{latestPrice:"Last Price",connecting:"Connecting to market feed",publicFeed:"Free public market source · data may be delayed",open:"Open",high:"High",low:"Low",turnover:"Turnover Rate",volumeRatio:"Volume Ratio",fiveDays:"5 Days",twentyDays:"20 Days",recentMovement:"Recent Price Movement",lastDays:(count:number)=>`Last ${count} trading days · forward-adjusted`,historyLoading:"Loading historical prices; retrying automatically if needed…",historyUnavailable:"Historical prices are temporarily unavailable. Please try again.",historyInsufficient:(count:number)=>`Only ${count} trading day was retrieved, which is not enough to draw a trend. Trying the backup market source.`,historyStale:(date:string)=>`Historical price refresh is delayed. Showing saved data through ${date}.`,forwardAdjusted:"Forward-adjusted",retry:"Reconnect",retrying:"Retrying…",leaderLogic:"Industry Leadership Rationale",coreView:"Core Assessment",moveReview:"Movement Review",marketFacts:"Observed Market Facts",matchedSource:"Matched Source",noThreshold:"No movement threshold has been triggered, or market data is still connecting.",noPrediction:"The system matches observable facts only; it does not predict prices.",researchNote:"Research Note",disclaimer:"Inclusion indicates industry-research relevance, not reasonable valuation or a recommendation to buy. Review company filings, financial data and your own risk tolerance independently.",newsAndFilings:"Company News & Filings",recentNews:"Recent News",companyFilings:"Company Filings",noRelatedNews:"No related news was retrieved.",noFilings:"No recent filings were retrieved.",chartAria:"Recent closing-price chart. Use a mouse, touch, or the left and right arrow keys to inspect daily open, close, high and low prices.",priceUnit:"Price (CNY)",openShort:"O",closeShort:"C",highShort:"H",lowShort:"L",changeShort:"Chg"},
} as const;
