"use client";
import { useEffect, useMemo, useState } from "react";
type Quote={price:number|null;changePct:number|null;amount:number|null;turnover:number|null;volumeRatio:number|null;updatedAt:string};
type Company={mappingId:number;code:string;name:string;thesis:string;sectorId:number;sectorSlug:string;sectorName:string;sectorShortName:string;role:"core"|"candidate";rationale:string;quote:Quote|null};
type Sector={id:number;slug:string;name:string;shortName:string;description:string;count:number;coreCount:number;changePct:number|null};
type News={id:string;title:string;summary:string;time:string;source:string;url:string};
type Anomaly=Company&{interpretation:{facts:string;evidence:string;verified:boolean}|null;relatedNews:News|null};
type MarketData={companies:Company[];sectors:Sector[];news:News[];anomalies:Anomaly[];source:"live"|"unavailable";updatedAt:string};
export default function HomeDashboard(){
 const[data,setData]=useState<MarketData|null>(null),[error,setError]=useState(""),[sector,setSector]=useState("all"),[role,setRole]=useState("all"),[search,setSearch]=useState("");
 const load=()=>fetch("/api/market",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error||"数据加载失败");return r.json()}).then(d=>{setData(d);setError("")}).catch(e=>setError(e.message));
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const companies=useMemo(()=>{const rows=data?.companies??[];return rows.filter(c=>(sector==="all"||c.sectorSlug===sector)&&(role==="all"||c.role===role)&&(!search||`${c.name}${c.code}${c.sectorName}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>{const av=a.quote?.changePct,bv=b.quote?.changePct;if(av==null)return 1;if(bv==null)return-1;return bv-av})},[data,sector,role,search]);
 const uniqueCount=new Set((data?.companies??[]).map(c=>c.code)).size||80,market=marketState();
 return <main><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">算</span><span>算力图谱</span><em>COMPUTE CHAIN</em></a><nav aria-label="主导航"><a className="active" href="#overview">产业全景</a><a href="#signals">异动雷达</a><a href="#news">产业资讯</a><a className="admin-link" href="/admin">管理标的</a></nav></header>
 <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span/>A股算力产业研究终端</p><h1>算力产业链重点上市公司监测</h1><p className="lede">以细分市场份额和产业地位为基础，追踪13个产业环节重点A股公司的行情变化、异动证据与相关新闻。</p><div className="hero-actions"><a className="primary-button" href="#overview">浏览产业图谱 <span>↘</span></a><button className="refresh-button" onClick={load}>刷新数据</button><span className="market-status"><i className={market.open?"live-dot":""}/>{market.label} · {data?.source==="live"?"行情已连接":"等待行情源"}</span></div></div><div className="hero-metrics"><div><span>追踪标的</span><strong>{String(uniqueCount).padStart(2,"0")}</strong><small>家 A 股公司</small></div><div><span>产业环节</span><strong>{data?.sectors.length??13}</strong><small>覆盖完整链条</small></div><div><span>今日异动</span><strong>{String(data?.anomalies.length??0).padStart(2,"0")}</strong><small>{data?.anomalies.filter(a=>a.interpretation?.verified).length??0} 条已匹配证据</small></div><p>数据源状态 <b>{data?.source==="live"?"实时行情正常":"正在重试"}</b></p></div></section>
 <section className="sector-overview"><button className={sector==="all"?"selected":""} onClick={()=>{setSector("all");document.querySelector("#overview")?.scrollIntoView()}}><span>00</span><h3>全部方向</h3><p>查看算力产业链13个关键环节的全部重点上市公司。</p><footer><b>{uniqueCount} 家标的</b><em>产业全景</em></footer></button>{(data?.sectors??[]).map((s,i)=><button className={sector===s.slug?"selected":""} key={s.id} onClick={()=>{setSector(s.slug);document.querySelector("#overview")?.scrollIntoView()}}><span>{String(i+1).padStart(2,"0")}</span><h3>{s.shortName}</h3><p>{s.description}</p><footer><b>{s.count} 家标的</b><em className={(s.changePct??0)>=0?"up":"down"}>{s.changePct===null?"行情待更新":`${signed(s.changePct)}%`}</em></footer></button>)}</section>
 <section className="dashboard" id="overview"><div className="section-heading"><div><p className="eyebrow"><span/>CORE LEADERS</p><h2>{sector==="all"?"产业核心标的":data?.sectors.find(s=>s.slug===sector)?.name}</h2></div><p>产业地位与盘面变化双层呈现。<br/>行情交易时段每 30 秒刷新。</p></div><div className="toolbar"><div className="segmented"><button className={role==="all"?"active":""} onClick={()=>setRole("all")}>全部</button><button className={role==="core"?"active":""} onClick={()=>setRole("core")}>产业核心</button><button className={role==="candidate"?"active":""} onClick={()=>setRole("candidate")}>市场活跃</button></div><label className="search-box"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索公司、代码或环节"/></label></div>{error&&<div className="data-notice">数据暂时没有连接成功：{error}。页面会自动重试。</div>}<div className="leader-table" role="table"><div className="table-head" role="row"><span>公司 / 代码</span><span>产业环节</span><span>最新价</span><span>今日涨跌</span><span>成交额</span><span>身份</span></div>{companies.map((c,i)=><a className="table-row" href={`/company/${c.code}`} role="row" key={`${c.code}-${c.sectorId}`}><span className="company-cell"><i>{String(i+1).padStart(2,"0")}</i><b>{c.name}<small>{c.code} · {c.quote?.updatedAt?timeOnly(c.quote.updatedAt):"等待行情"}</small></b></span><span><em className="sector-tag">{c.sectorShortName}</em></span><strong>{c.quote?.price==null?"—":`¥ ${formatPrice(c.quote.price)}`}</strong><span className={(c.quote?.changePct??0)>=0?"up":"down"}>{c.quote?.changePct==null?"—":`${signed(c.quote.changePct)}%`}</span><span className="amount">{formatAmount(c.quote?.amount)}</span><span className={c.role==="core"?"verified":"candidate"}>{c.role==="core"?"产业核心":"活跃候选"}</span></a>)}{!companies.length&&<div className="empty-state">没有匹配的标的</div>}</div></section>
 <section className="signals" id="signals"><div className="section-heading light"><div><p className="eyebrow"><span/>EVIDENCE FIRST</p><h2>异动雷达</h2></div><p>只呈现可观察事实与可追溯信息。<br/>无可靠证据时不强行归因。</p></div><div className="signal-grid">{(data?.anomalies??[]).map(a=><a href={`/company/${a.code}`} className="signal-card" key={`${a.code}-${a.sectorId}`}><header><span>{a.sectorShortName}</span><b className={(a.quote?.changePct??0)>=0?"up":"down"}>{signed(a.quote?.changePct??0)}%</b></header><h3>{a.name}<small>{a.code}</small></h3><p>{a.interpretation?.facts}</p>{a.interpretation?.verified&&<footer className="has-evidence"><i/>{a.interpretation.evidence}</footer>}</a>)}{!(data?.anomalies.length)&&<div className="signals-empty"><strong>暂无显著异动</strong><span>触发条件：涨跌幅绝对值 ≥ 3% 或量比 ≥ 1.8</span></div>}</div></section>
 <section className="news-section" id="news"><div className="section-heading"><div><p className="eyebrow"><span/>INDUSTRY INTELLIGENCE</p><h2>产业重要资讯</h2></div><p>新闻来自公开财经资讯源。<br/>点击跳转原文核验。</p></div><div className="news-list">{(data?.news??[]).slice(0,10).map((n,i)=><a href={n.url} target="_blank" rel="noreferrer" key={n.id||i}><time>{newsTime(n.time)}</time><div><h3>{n.title}</h3>{n.summary&&<p>{n.summary.slice(0,110)}</p>}</div><span>{n.source} ↗</span></a>)}{!data?.news.length&&<div className="empty-state">资讯源暂时不可用，页面会自动重试。</div>}</div></section>
 <footer className="site-footer"><a className="brand" href="#top"><span className="brand-mark">算</span><span>算力图谱</span></a><p>数据仅供产业研究与信息参考，不构成任何投资建议。行情可能存在延迟，请以交易所及持牌机构数据为准。</p><span>© 2026 COMPUTE CHAIN</span></footer></main>}
function signed(v:number){return`${v>=0?"+":""}${v.toFixed(2)}`}function formatPrice(v:number){return v.toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}function formatAmount(v:number|null|undefined){if(v==null)return"—";return v>=1e8?`${(v/1e8).toFixed(1)}亿`:`${(v/1e4).toFixed(0)}万`}function timeOnly(v:string){return new Date(v).toLocaleTimeString("zh-CN",{timeZone:"Asia/Shanghai",hour:"2-digit",minute:"2-digit"})}function newsTime(v:string){if(!v)return"刚刚";const d=new Date(v);return Number.isNaN(d.getTime())?v.slice(5,16):d.toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}function marketState(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date()),val=(t:string)=>p.find(x=>x.type===t)?.value??"",m=Number(val("hour"))*60+Number(val("minute")),w=val("weekday"),open=!/[SatSun]/.test(w)&&((m>=570&&m<=690)||(m>=780&&m<=900));return{open,label:open?"交易中":"已收盘"}}
